export const SET_USER = 'SET_USER'
export const SET_VERIFIED = 'SET_VERIFIED'

export const SET_USERS = 'SET_USERS'
export const REMOVE_USER = 'REMOVE_USER'

export const SET_COURSES = 'SET_COURSES'
export const ADD_COURSE = 'ADD_COURSE'
export const REMOVE_COURSE = 'REMOVE_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const REMOVE_STUDENT = 'REMOVE_STUDENT'

export const SET_EXAMS = 'SET_EXAMS'
export const ADD_EXAM = 'ADD_EXAM'
export const REMOVE_EXAM = 'REMOVE_EXAM'

export const SET_ATTEMPTS = 'SET_ATTEMPTS'
export const ADD_ATTEMPT = 'ADD_ATTEMPT'
export const UPDATE_ATTEMPT = 'UPDATE_ATTEMPT'
export const REMOVE_ATTEMPTS_BY_EXAM = 'REMOVE_ATTEMPTS_BY_EXAM'

export const SET_ACTIVE_EXAM = 'SET_ACTIVE_EXAM'

export const SET_EXAM_RESULTS = 'SET_EXAM_RESULTS'
export const ADD_EXAM_RESULT = 'ADD_EXAM_RESULT'
export const REMOVE_EXAM_RESULTS_BY_EXAM = 'REMOVE_EXAM_RESULTS_BY_EXAM'

export const SET_MESSAGE = 'SET_MESSAGE'

export const SET_THEME = 'SET_THEME'
