export const SET_USER = 'SET_USER'

export const SET_COURSES = 'SET_COURSES'
export const REMOVE_COURSE = 'REMOVE_COURSE'

export const SET_EXAM_ITEMS = 'SET_EXAM_ITEMS'
export const SET_EXAMS = 'SET_EXAMS'

export const SET_ATTEMPTS = 'SET_ATTEMPTS'
export const ADD_ATTEMPT = 'ADD_ATTEMPT'
export const UPDATE_ATTEMPT = 'UPDATE_ATTEMPT'

export const SET_ACTIVE_EXAM = 'SET_ACTIVE_EXAM'

export const SET_EXAM_RESULTS = 'SET_EXAM_RESULTS'
export const ADD_EXAM_RESULT = 'ADD_EXAM_RESULT'

export const DISPLAY_DIALOG = 'DISPLAY_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

export const SET_RECENT_COURSES = 'SET_RECENT_COURSES'
export const ADD_RECENT_COURSE = 'ADD_RECENT_COURSE'

export const SET_MESSAGE = 'SET_MESSAGE'

export const SET_THEME = 'SET_THEME'
