<template>
  <button
    class="
      flex
      justify-center
      items-center
      text-indigo-600
      dark:text-indigo-400
      focus:outline-none
      disabled:opacity-50
      disabled:pointer-events-none
    "
  >
    <slot></slot>
  </button>
</template>
